from typing import Any

from app.db.models.enums import (
    BodyType,
    DrivetrainType,
    EmissionStandard,
    FuelType,
    SegmentType,
    TransmissionType,
    VehicleStatus,
)

# maps category -> field_name -> (type_converter, extra_param_or_default)
FIELD_RULES: dict[str, dict[str, tuple[str, Any]]] = {
    "brand": {
        "name": ("text", None),
        "country": ("text", "Unknown"),
        "origin": ("text", None),
    },
    "vehicle": {
        "model": ("text", None),
        "variant": ("text", None),
        "year": ("int", None),
        "body_type": ("enum", BodyType),
        "segment": ("enum", SegmentType),
        "fuel_type": ("enum", FuelType),
        "transmission": ("enum", TransmissionType),
        "drivetrain": ("enum", DrivetrainType),
        "seating_capacity": ("int", None),
        "doors": ("int", None),
        "price_ex_showroom": ("decimal", None),
        "price_on_road": ("decimal", None),
    },
    "engine_spec": {
        "engine_cc": ("int", None),
        "cylinders": ("int", None),
        "power_bhp": ("float", None),
        "torque_nm": ("float", None),
        "mileage_kmpl": ("float", None),
        "top_speed_kmph": ("int", None),
        "acceleration_0_100_sec": ("float", None),
        "fuel_tank_capacity_l": ("float", None),
        "emission_norm": ("text", None),
    },
    "dimension_spec": {
        "length_mm": ("int", None),
        "width_mm": ("int", None),
        "height_mm": ("int", None),
        "wheelbase_mm": ("int", None),
        "ground_clearance_mm": ("int", None),
        "boot_space_l": ("int", None),
        "kerb_weight_kg": ("int", None),
        "turning_radius_m": ("float", None),
    },
    "safety_spec": {
        "airbags": ("int", None),
        "abs": ("bool", None),
        "esc": ("bool", None),
        "traction_control": ("bool", None),
        "hill_hold_control": ("bool", None),
        "hill_descent_control": ("bool", None),
        "isofix": ("bool", None),
        "tpms": ("bool", None),
        "blind_spot_monitor": ("bool", None),
        "lane_keep_assist": ("bool", None),
        "adaptive_cruise_control": ("bool", None),
        "autonomous_emergency_braking": ("bool", None),
        "adas_level": ("int", None),
        "safety_rating": ("float", None),
    },
    "feature_spec": {
        "android_auto": ("bool", None),
        "apple_carplay": ("bool", None),
        "wireless_android_auto": ("bool", None),
        "wireless_apple_carplay": ("bool", None),
        "touchscreen_size_in": ("float", None),
        "digital_instrument_cluster": ("bool", None),
        "climate_control": ("bool", None),
        "ventilated_seats": ("bool", None),
        "powered_driver_seat": ("bool", None),
        "sunroof": ("bool", None),
        "panoramic_sunroof": ("bool", None),
        "wireless_charging": ("bool", None),
        "keyless_entry": ("bool", None),
        "push_button_start": ("bool", None),
        "cruise_control": ("bool", None),
        "parking_camera": ("bool", None),
        "camera_360": ("bool", None),
        "parking_sensors": ("bool", None),
    },
    "ownership_spec": {
        "warranty_years": ("int", None),
        "warranty_km": ("int", None),
        "extended_warranty_available": ("bool", None),
        "service_interval_km": ("int", None),
        "roadside_assistance": ("bool", None),
        "estimated_service_cost_per_year": ("decimal", None),
    },
    "availability_spec": {
        "launch_year": ("int", None),
        "current_status": ("enum", VehicleStatus),
        "booking_open": ("bool", None),
        "waiting_period_weeks": ("int", None),
    },
    "environmental_spec": {
        "emission_standard": ("enum", EmissionStandard),
        "co2_emissions_gkm": ("float", None),
        "battery_capacity_kwh": ("float", None),
        "electric_range_km": ("int", None),
        "charging_time_ac_hr": ("float", None),
        "charging_time_dc_min": ("int", None),
    },
}
