"""Initial database schema

Revision ID: 2ee8be84e536
Revises:
Create Date: 2026-07-22 17:09:14.718240

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2ee8be84e536"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("origin", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "vehicles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("variant", sa.String(length=100), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "body_type",
            sa.Enum(
                "HATCHBACK",
                "SEDAN",
                "SUV",
                "MUV",
                "COUPE",
                "CONVERTIBLE",
                "PICKUP",
                name="bodytype",
            ),
            nullable=False,
        ),
        sa.Column(
            "segment",
            sa.Enum("A", "B", "C", "D", "E", "PREMIUM", "LUXURY", name="segmenttype"),
            nullable=False,
        ),
        sa.Column(
            "fuel_type",
            sa.Enum(
                "PETROL",
                "DIESEL",
                "CNG",
                "EV",
                "HYBRID",
                "PLUGIN_HYBRID",
                name="fueltype",
            ),
            nullable=False,
        ),
        sa.Column(
            "transmission",
            sa.Enum(
                "MANUAL", "AUTOMATIC", "AMT", "CVT", "DCT", name="transmissiontype"
            ),
            nullable=False,
        ),
        sa.Column("drivetrain", sa.String(length=30), nullable=True),
        sa.Column("seating_capacity", sa.Integer(), nullable=False),
        sa.Column("doors", sa.Integer(), nullable=False),
        sa.Column(
            "price_ex_showroom", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("price_on_road", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "brand_id",
            "model",
            "variant",
            "year",
            name="uq_vehicles_brand_model_variant_year",
        ),
    )
    op.create_index("ix_vehicles_fuel_type", "vehicles", ["fuel_type"], unique=False)
    op.create_index("ix_vehicles_model", "vehicles", ["model"], unique=False)
    op.create_index(
        "ix_vehicles_price_ex_showroom", "vehicles", ["price_ex_showroom"], unique=False
    )
    op.create_index(
        "ix_vehicles_transmission", "vehicles", ["transmission"], unique=False
    )
    op.create_table(
        "dimension_specs",
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("length_mm", sa.Integer(), nullable=True),
        sa.Column("width_mm", sa.Integer(), nullable=True),
        sa.Column("height_mm", sa.Integer(), nullable=True),
        sa.Column("wheelbase_mm", sa.Integer(), nullable=True),
        sa.Column("ground_clearance_mm", sa.Integer(), nullable=True),
        sa.Column("boot_space_l", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("vehicle_id"),
    )
    op.create_table(
        "engine_specs",
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("engine_cc", sa.Integer(), nullable=True),
        sa.Column("cylinders", sa.Integer(), nullable=True),
        sa.Column("power_bhp", sa.Float(), nullable=True),
        sa.Column("torque_nm", sa.Float(), nullable=True),
        sa.Column("mileage_kmpl", sa.Float(), nullable=True),
        sa.Column("fuel_tank_l", sa.Float(), nullable=True),
        sa.Column("emission_norm", sa.String(length=30), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("vehicle_id"),
    )
    op.create_table(
        "feature_specs",
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("sunroof", sa.Boolean(), nullable=True),
        sa.Column("ventilated_seats", sa.Boolean(), nullable=True),
        sa.Column("automatic_climate_control", sa.Boolean(), nullable=True),
        sa.Column("touchscreen_inches", sa.Float(), nullable=True),
        sa.Column("wireless_android_auto", sa.Boolean(), nullable=True),
        sa.Column("wireless_apple_carplay", sa.Boolean(), nullable=True),
        sa.Column("cruise_control", sa.Boolean(), nullable=True),
        sa.Column("parking_camera", sa.Boolean(), nullable=True),
        sa.Column("parking_sensors", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("vehicle_id"),
    )
    op.create_table(
        "ownership_specs",
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("warranty_years", sa.Integer(), nullable=True),
        sa.Column("warranty_km", sa.Integer(), nullable=True),
        sa.Column("service_interval_km", sa.Integer(), nullable=True),
        sa.Column("roadside_assistance", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("vehicle_id"),
    )
    op.create_table(
        "safety_specs",
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("airbags", sa.Integer(), nullable=True),
        sa.Column("abs", sa.Boolean(), nullable=True),
        sa.Column("esc", sa.Boolean(), nullable=True),
        sa.Column("traction_control", sa.Boolean(), nullable=True),
        sa.Column("adas_level", sa.Integer(), nullable=True),
        sa.Column("safety_rating", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("vehicle_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("safety_specs")
    op.drop_table("ownership_specs")
    op.drop_table("feature_specs")
    op.drop_table("engine_specs")
    op.drop_table("dimension_specs")
    op.drop_index("ix_vehicles_transmission", table_name="vehicles")
    op.drop_index("ix_vehicles_price_ex_showroom", table_name="vehicles")
    op.drop_index("ix_vehicles_model", table_name="vehicles")
    op.drop_index("ix_vehicles_fuel_type", table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_table("brands")
    # ### end Alembic commands ###
